[build]
builder = "nixpacks"
buildCommand = "./gradlew clean build -x test"

[deploy]
startCommand = "java -jar build/libs/tournament-app-backend-1.0.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
