name: Deploy Spring Boot to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    #if: contains(github.event.head_commit.message, '[server]')
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./server

      # Build the Spring Boot Application
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: ./server

      # Überprüfe die Verzeichnisstruktur nach dem Build
      - name: List build libs directory
        run: ls -R build/libs
        working-directory: ./server

      # Find the latest JAR file
      - name: Find JAR file
        id: find_jar
        run: echo "jarfile=$(ls ./server/build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tournament-app-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.jarfile }}
