name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Set Environment Variables Step
      - name: Set Environment Variables
        run: echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        working-directory: ./client

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      # Create env.js file
      - name: Create env.js
        run: |
          echo "window.env = { API_URL: '$(echo $API_URL)' };" > ./assets/env.js
        working-directory: ./client

      # Build the Angular App
      - name: Build Angular App
        run: npm run build --configuration=production
        working-directory: ./client

      # Move env.js to dist after build
      - name: Move env.js to dist folder
        run: cp ./src/assets/env.js ./dist/tournament/browser/assets/env.js
        working-directory: ./client

      # Build And Deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_0CC58BE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./client"
          api_location: ""
          output_location: "dist/tournament/browser"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_0CC58BE03 }}
          action: "close"
